/* Parameters */
constellations.maxNumOfSteps = 400;
constellations.minDistance = 5;
constellations.maxDistance = 15;
constellations.maxConnections = 20;
constellations.speed = 10;
constellations.worldSizeMax = 100;
constellations.worldSizeMin = 50;
constellations.hideStars = false;
constellations.lineColor = 'yellow';
constellations.sphereColor = 'white';
